[tool.briefcase]
project_name = "P2PP - Palette 2 Post Processor"
bundle = "com.tomvandeneede.p2pp"
version = "5.0"
author = "Tom Van den Eede/Tim Brookmanr"
author_email = "t.vandeneede@pandora.be"
requires = []

[tool.briefcase.app.p2pp]
formal_name = "P2PP"
description = "Palette2(Pro) Post Processor for Prusa Slicer"
requires = []
sources = ['P2PP.py', 'version.py', 'configurator.py',  'p2pp.command', 'p2pp.bat',]

[tool.briefcase.app.p2pp.macOS]
requires = ['toga-cocoa==0.3.0.dev15']

[tool.briefcase.app.p2pp.windows]
requires = ['toga-winforms==0.3.0.dev15']